version: "3.7"

# Database + Webserver (under http, for testing setup on localhost:80)
#
# docker-compose -f docker-compose.dev.yml up -d
#

services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./database/.env.dev
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
  backend:
    depends_on:
      - postgres
    restart: "unless-stopped"
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - DEFAULT_DATABASE_HOSTNAME=postgres
      - DEFAULT_DATABASE_PORT=5432

volumes:
  postgres_data:
