version: "3.7"

# Database + Webserver (under http, for testing setup on localhost:80)
#
# docker-compose -f docker-compose.dev.yml up -d
#

services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./database/.env.dev
  backend:
    depends_on:
      - postgres
    restart: "unless-stopped"
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - DEFAULT_DATABASE_HOSTNAME=postgres
      - DEFAULT_DATABASE_PORT=5432
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./backend:/build
    ports:
      - "8000:8000"
  frontend:
    restart: unless-stopped
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "3010:3010"

volumes:
  postgres_data:
