"""Usage start time embedded

Revision ID: 164b3a96928f
Revises: 8a9500fceb37
Create Date: 2024-12-20 01:58:41.092161

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "164b3a96928f"
down_revision = "8a9500fceb37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "machine_usages",
        sa.Column(
            "time_started",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("machine_usages", "time_started")
    # ### end Alembic commands ###
