"""Resource Usage Quantities and Maintenance Mode

Revision ID: 00ac28dee474
Revises: 0d9c1f8a5af1
Create Date: 2024-09-14 17:49:13.601065

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00ac28dee474"
down_revision = "0d9c1f8a5af1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "machines", sa.Column("maintenance_mode", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "resource_usage_quantities",
        sa.Column("amount", sa.DECIMAL(precision=15, scale=5), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource_usage_quantities", "amount")
    op.drop_column("machines", "maintenance_mode")
    # ### end Alembic commands ###
