"""Added Machine Types and Groups

Revision ID: 1ba3369a41f9
Revises: 7b8c2113c65f
Create Date: 2024-09-14 05:02:38.808474

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ba3369a41f9"
down_revision = "7b8c2113c65f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machine_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "machine_type_slot_associations",
        sa.Column("machine_type_id", sa.UUID(), nullable=False),
        sa.Column("resource_slot_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machine_type_id"],
            ["machine_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_slot_id"],
            ["resource_slots.id"],
        ),
        sa.PrimaryKeyConstraint("machine_type_id", "resource_slot_id"),
    )
    op.add_column("machine_types", sa.Column("name", sa.String(), nullable=False))
    op.create_unique_constraint("uq_machine_types_name", "machine_types", ["name"])
    op.add_column("machines", sa.Column("group_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        "fk_machines_machinegroups", "machines", "machine_groups", ["group_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_machines_machinegroups", "machines", type_="foreignkey")
    op.drop_column("machines", "group_id")
    op.drop_constraint("uq_machine_types_name", "machine_types", type_="unique")
    op.drop_column("machine_types", "name")
    op.drop_table("machine_type_slot_associations")
    op.drop_table("machine_groups")
    # ### end Alembic commands ###
