"""Postgres decimal settings have dumb names

Revision ID: 0d9c1f8a5af1
Revises: ee815da04266
Create Date: 2024-09-14 05:44:12.455029

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d9c1f8a5af1"
down_revision = "ee815da04266"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resources",
        "cost",
        existing_type=sa.NUMERIC(precision=5, scale=10),
        type_=sa.DECIMAL(precision=10, scale=5),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resources",
        "cost",
        existing_type=sa.DECIMAL(precision=10, scale=5),
        type_=sa.NUMERIC(precision=5, scale=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
