"""Make usage semester optional in db for admin use

Revision ID: 8a9500fceb37
Revises: 705c79f09e28
Create Date: 2024-12-20 01:09:15.256604

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a9500fceb37"
down_revision = "705c79f09e28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "machine_usages", "semester_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "machine_usages", "semester_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
