"""Fixes foreign key overlap issue

Revision ID: fee16fdc02c6
Revises: 3aae57c1edcd
Create Date: 2024-01-27 00:22:52.783885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fee16fdc02c6"
down_revision = "3aae57c1edcd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("machines", sa.Column("active_usage_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_active_usage", "machines", "machine_usages", ["active_usage_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_active_usage", "machines", type_="foreignkey")
    op.drop_column("machines", "active_usage_id")
    # ### end Alembic commands ###
