"""Minor updates

Revision ID: ee815da04266
Revises: 1ba3369a41f9
Create Date: 2024-09-14 05:29:37.383404

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee815da04266"
down_revision = "1ba3369a41f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resources", "brand", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint("uq_resources", "resources", ["brand", "name", "units"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_resources", "resources", type_="unique")
    op.alter_column("resources", "brand", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
