"""machine usage keys updates

Revision ID: 29da92db7ac9
Revises: 164b3a96928f
Create Date: 2024-12-29 01:51:29.779605

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "29da92db7ac9"
down_revision = "164b3a96928f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "machine_usages", sa.Column("failed_at", sa.DateTime(), nullable=True)
    )
    op.add_column("machines", sa.Column("active_usage_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "machines", "machine_usages", ["active_usage_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "machines", type_="foreignkey")
    op.drop_column("machines", "active_usage_id")
    op.drop_column("machine_usages", "failed_at")
    # ### end Alembic commands ###
