"""Add unique default to state

Revision ID: 84033fc4515d
Revises: eda8563b9ca8
Create Date: 2025-05-02 22:38:04.964444

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84033fc4515d"
down_revision = "eda8563b9ca8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "machines", ["active_usage_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "machines", type_="unique")
    # ### end Alembic commands ###
