"""Removed unnecessary semester info

Revision ID: eda8563b9ca8
Revises: 6eceebb82f1b
Create Date: 2025-01-26 01:31:08.855086

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eda8563b9ca8"
down_revision = "6eceebb82f1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_semester_associations")
    op.drop_table("org_semester_associations")
    op.create_unique_constraint(None, "semesters", ["semester_type", "calendar_year"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "semesters", type_="unique")
    op.create_table(
        "org_semester_associations",
        sa.Column("org_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("semester_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name="org_semester_associations_org_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name="org_semester_associations_semester_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "org_id", "semester_id", name="org_semester_associations_pkey"
        ),
    )
    op.create_table(
        "user_semester_associations",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("semester_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name="user_semester_associations_semester_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="user_semester_associations_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "semester_id", name="user_semester_associations_pkey"
        ),
    )
    # ### end Alembic commands ###
