"""Add checked_graduating to users

Revision ID: 8d1c2a4b7f6e
Revises: 04280ccacd1e
Create Date: 2026-05-22 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8d1c2a4b7f6e"
down_revision = "04280ccacd1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "checked_graduating",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "checked_graduating")
    # ### end Alembic commands ###